[server]
headless = true
port = 8501
enableCORS = false
maxUploadSize = 200

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#00FF41"
backgroundColor = "#000000"
secondaryBackgroundColor = "#0d1117"
textColor = "#00FF41"
font = "monospace"